version: '3.8'

services:
  alfa.test:
    build:
      context: './docker/8.4'
      dockerfile: Dockerfile
      args:
        WWWGROUP: '${WWWGROUP}'
    image: 'sail-8.4/app'
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    environment:
      WWWUSER: '${WWWUSER}'
      LARAVEL_SAIL: 1
      XDEBUG_MODE: '${SAIL_XDEBUG_MODE:-off}'
      XDEBUG_CONFIG: '${SAIL_XDEBUG_CONFIG:-client_host=host.docker.internal}'
      IGNITION_LOCAL_SITES_PATH: '${PWD}'
      APP_ENV: testing
      DB_CONNECTION: mysql
      DB_HOST: mysql.test
      DB_PORT: 3306
      DB_DATABASE: alfa_manager_test
      DB_USERNAME: sail
      DB_PASSWORD: password
    volumes:
      - '.:/var/www/html'
    networks:
      - sail-test
    depends_on:
      mysql.test:
        condition: service_healthy
    command: tail -f /dev/null

  mysql.test:
    image: 'mysql/mysql-server:8.0'
    environment:
      MYSQL_ROOT_PASSWORD: 'password'
      MYSQL_ROOT_HOST: '%'
      MYSQL_DATABASE: 'alfa_manager_test'
      MYSQL_USER: 'sail'
      MYSQL_PASSWORD: 'password'
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
    volumes:
      - 'sail-mysql-test:/var/lib/mysql'
      - './vendor/laravel/sail/database/mysql/create-testing-database.sh:/docker-entrypoint-initdb.d/10-create-testing-database.sh'
    networks:
      - sail-test
    healthcheck:
      test:
        - CMD
        - mysqladmin
        - ping
        - '-p${DB_PASSWORD}'
      retries: 3
      timeout: 5s

networks:
  sail-test:
    driver: bridge

volumes:
  sail-mysql-test:
    driver: local 